version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swapi-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL_SECONDS=86400
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server
    restart: always
